/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: antonmoek (https://sketchfab.com/antonmoek)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cartoon-plane-f312ec9f87794bdd83630a3bc694d8ea
title: Cartoon Plane
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/plane/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0}>
          <group name="12cc6a9ff2ae45b08826ba235d9cb8b7fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Propeller_1" position={[0.87, -46.02, 401.43]}>
                  <mesh name="Propeller_1_Red_0" geometry={nodes.Propeller_1_Red_0.geometry} material={materials.material} />
                  <mesh name="Propeller_1_Body_0" geometry={nodes.Propeller_1_Body_0.geometry} material={materials.Body} />
                </group>
                <group name="Physical_Sky" rotation={[-0.05, -0.5, 0]}>
                  <group name="Sky_Null" position={[195.25, 64.46, 239.45]}>
                    <group name="Sun" position={[-8659.81, 52407.36, 138158.2]} rotation={[-0.36, -0.06, -0.02]} />
                    <group name="Moon" position={[-3951.26, 517.19, -640.6]} rotation={[-2.46, -1.37, -2.47]} />
                  </group>
                  <group name="Shadow_Plane" position={[0, 10000, 0]} />
                </group>
                <group name="Plane" position={[-2.54, -22.78, 0]}>
                  <group name="Wheel_Back" position={[3.22, -59.61, -256.32]} rotation={[0.17, 0, -0.02]}>
                    <group name="Cylinder_1" position={[6.52, -27.54, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                      <mesh name="Cylinder_1_Body_0" geometry={nodes.Cylinder_1_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="WheelCarcas" position={[114.39, 59.17, 0]}>
                      <mesh name="WheelCarcas_Body_0" geometry={nodes.WheelCarcas_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="Wheel" position={[0.62, -32.49, 0]} rotation={[0, 0, -Math.PI / 2]}>
                      <mesh name="Wheel_Gum_0" geometry={nodes.Wheel_Gum_0.geometry} material={materials.material_3} />
                    </group>
                  </group>
                  <group name="Wheel_1" position={[81.31, -76.38, 232.74]} rotation={[0, 0, 0.33]}>
                    <group name="Cylinder_1_2" position={[12.17, -51.44, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                      <mesh name="Cylinder_1_2_Body_0" geometry={nodes.Cylinder_1_2_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="WheelCarcas_2" position={[213.61, 110.5, 0]}>
                      <mesh name="WheelCarcas_2_Body_0" geometry={nodes.WheelCarcas_2_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="Wheel_2" position={[1.16, -60.67, 0]} rotation={[0, 0, -Math.PI / 2]}>
                      <mesh name="Wheel_2_Gum_0" geometry={nodes.Wheel_2_Gum_0.geometry} material={materials.material_3} />
                    </group>
                  </group>
                  <group name="Wheel_3" position={[-81.57, -76.38, 232.74]} rotation={[0, 0, -0.32]}>
                    <group name="Cylinder_1_3" position={[12.17, -51.44, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                      <mesh name="Cylinder_1_3_Body_0" geometry={nodes.Cylinder_1_3_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="WheelCarcas_3" position={[213.61, 110.5, 0]}>
                      <mesh name="WheelCarcas_3_Body_0" geometry={nodes.WheelCarcas_3_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="Wheel_4" position={[1.16, -60.67, 0]} rotation={[0, 0, -Math.PI / 2]}>
                      <mesh name="Wheel_4_Gum_0" geometry={nodes.Wheel_4_Gum_0.geometry} material={materials.material_3} />
                    </group>
                  </group>
                  <group name="Air_motor_right" position={[0, -45.57, 0]} rotation={[0, 0, -Math.PI]}>
                    <group name="Cube_2">
                      <mesh name="Cube_2_Body_0" geometry={nodes.Cube_2_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="Cube_1">
                      <mesh name="Cube_1_Body_0" geometry={nodes.Cube_1_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="Cube">
                      <mesh name="Cube_Body_0" geometry={nodes.Cube_Body_0.geometry} material={materials.Body} />
                    </group>
                  </group>
                  <group name="Air_motor_left" position={[0, 22.78, 0]}>
                    <group name="Cube_2_2">
                      <mesh name="Cube_2_2_Body_0" geometry={nodes.Cube_2_2_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="Cube_1_2">
                      <mesh name="Cube_1_2_Body_0" geometry={nodes.Cube_1_2_Body_0.geometry} material={materials.Body} />
                    </group>
                    <group name="Cube_2_3">
                      <mesh name="Cube_2_3_Body_0" geometry={nodes.Cube_2_3_Body_0.geometry} material={materials.Body} />
                    </group>
                  </group>
                  <group name="Body" position={[0, 22.78, 0]}>
                    <group name="Cube_1_3">
                      <mesh name="Cube_1_3_Body_0" geometry={nodes.Cube_1_3_Body_0.geometry} material={materials.Body} />
                      <mesh name="Cube_1_3_Red_0" geometry={nodes.Cube_1_3_Red_0.geometry} material={materials.material} />
                      <mesh name="Cube_1_3_Glass_0" geometry={nodes.Cube_1_3_Glass_0.geometry} material={materials.Glass} />
                      <mesh name="Cube_1_3__0" geometry={nodes.Cube_1_3__0.geometry} material={materials.Cube_1_3__0} />
                    </group>
                    <group name="Cube_3">
                      <mesh name="Cube_3_Body_0" geometry={nodes.Cube_3_Body_0.geometry} material={materials.Body} />
                      <mesh name="Cube_3_Red_0" geometry={nodes.Cube_3_Red_0.geometry} material={materials.material} />
                      <mesh name="Cube_3_Glass_0" geometry={nodes.Cube_3_Glass_0.geometry} material={materials.Glass} />
                      <mesh name="Cube_3__0" geometry={nodes.Cube_3__0.geometry} material={materials.Cube_1_3__0} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/plane/scene.gltf')
