---
title: "Mauricio Poppe notes"

params:
  description: "Mauricio Poppe notes"
  favicon: "favicon/favicon.ico"
  logo: "https://www.mauriciopoppe.com/images/me-playing-guitar.png"
  author:
    name: "Mauricio Poppe"
    github: mauriciopoppe
    linkedin: mauriciopoppe
    twitter: mauricio_poppe
    youtube: mauricio-poppe

baseURL: "https://www.mauriciopoppe.com/"
languageCode: "en-us"

algolia:
  # https://dashboard.algolia.com/connectors
  index: "MY_INDEX"
  appID: "82T3453LSW"

metadataFormat: 'yaml'
enableGitInfo: true
summaryLength: 50

markup:
  highlight:
    # syntax is highlighted by prism
    codeFences: false
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false

related:
  includeNewer: yes
  indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: keywords
    pattern: ""
    toLower: false
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 0
    name: date
    pattern: ""
    toLower: false
    type: basic
    weight: 10
  - applyFilter: false
    cardinalityThreshold: 0
    name: tags
    pattern: ""
    toLower: false
    type: basic
    weight: 80
  threshold: 80
  toLower: false
---
